In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
import numpy as np

In [2]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [3]:
train_data.shape,train_labels.shape

((25000,), (25000,))

In [4]:
test_data.shape

(25000,)

In [5]:
np.unique(train_labels)

array([0, 1])

In [6]:
np.unique(test_data)

array([list([1, 2, 2, 2, 2, 4, 2, 393, 7, 6, 2, 1830, 39, 998, 2445, 1364, 656, 94, 58, 143, 4, 454, 17, 12, 144, 366, 75, 6050, 39, 2, 21, 5610, 1915, 5, 1398, 83, 2, 7, 1306, 5, 6, 483, 5564, 3411, 44, 4, 394, 2, 7, 2, 10, 10, 2, 7279, 5, 2, 638, 4, 8921, 2, 5096, 4, 330, 5, 2, 4, 529, 14, 9521, 370, 157, 9, 2, 11, 6, 2, 109, 37, 9, 1305, 4, 9824, 2, 27, 292, 33, 4, 8465, 1923, 5, 1200, 27, 223, 8, 605, 2, 95, 2, 174, 5, 3582, 8, 4, 5315, 1946, 7, 27, 430, 351, 10, 10, 6, 2, 154, 255, 2, 23, 41, 658, 5, 6, 185, 430, 1442, 154, 183, 413, 162, 5, 162, 183, 783, 469, 9, 4, 8921, 2, 17, 594, 8559, 17, 4, 479, 7, 438]),
       list([1, 2, 2, 2, 4, 31, 125, 1293, 29, 115, 93, 160, 22, 21, 1075, 6, 530, 3213, 7, 4717, 532, 3680, 11, 14, 22, 15, 9, 199, 2, 5, 7814, 29, 2, 4, 268, 5267, 4, 2, 2, 7, 6, 132, 2244, 180, 467, 4, 8869, 7, 35, 3437, 4045, 113, 10, 10, 723, 2, 9, 35, 3950, 1652, 871, 820, 2347, 3006, 2451, 5383, 6, 2, 3406, 2665, 19, 57, 281, 7, 4, 705, 8, 794, 27, 323, 240, 6, 4970

In [7]:
word_index = imdb.get_word_index()

In [8]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

In [9]:
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?') for i in train_data[0]])

In [10]:
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [11]:
train_labels[0]

1

In [12]:
trainx=np.zeros((25000,10000))
for idx,i in enumerate(train_data):
  trainx[idx,i]=1
  


In [13]:
trainx.shape

(25000, 10000)

In [14]:
testx=np.zeros((25000,10000))
for idx,i in enumerate(test_data):
  testx[idx,i]=1
  


In [15]:
testx

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [16]:
from keras.models import Sequential
from keras.layers import Dense,Dropout
model = Sequential()
model.add(Dense(32,input_shape=(10000,),activation='relu'))
model.add(Dropout(0.5))
#model.add(Dense(64,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2,activation='softmax'))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                320032    
_________________________________________________________________
dropout (Dropout)            (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
dropout_1 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 34        
Total params: 320,594
Trainable params: 320,594
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(trainx,train_labels,epochs=10,verbose=1,validation_data=(testx,test_labels))

Epoch 1/10
782/782 [==============================] - 6s 6ms/step - loss: 0.4882 - accuracy: 0.7565 - val_loss: 0.2793 - val_accuracy: 0.8837
Epoch 2/10
782/782 [==============================] - 4s 5ms/step - loss: 0.2392 - accuracy: 0.9076 - val_loss: 0.2889 - val_accuracy: 0.8805
Epoch 3/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1906 - accuracy: 0.9272 - val_loss: 0.3085 - val_accuracy: 0.8814
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1487 - accuracy: 0.9428 - val_loss: 0.3238 - val_accuracy: 0.8752
Epoch 5/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1309 - accuracy: 0.9486 - val_loss: 0.3521 - val_accuracy: 0.8771
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1192 - accuracy: 0.9523 - val_loss: 0.3697 - val_accuracy: 0.8754
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.0996 - accuracy: 0.9588 - val_loss: 0.3914 - val_accuracy: 0.8758
Epoch 

In [30]:
decoded_rev = ' '.join([reverse_word_index.get(i - 3, ' ') for i in test_data[0]])

In [31]:
decoded_rev

"  please give this one a miss br br     and the rest of the cast rendered terrible performances the show is flat flat flat br br i don't know how michael madison could have allowed this one on his plate he almost seemed to know this wasn't going to work out and his performance was quite   so all you madison fans give this a miss"

In [32]:
decoded_rev.split(' ')

['',
 '',
 'please',
 'give',
 'this',
 'one',
 'a',
 'miss',
 'br',
 'br',
 '',
 '',
 '',
 '',
 'and',
 'the',
 'rest',
 'of',
 'the',
 'cast',
 'rendered',
 'terrible',
 'performances',
 'the',
 'show',
 'is',
 'flat',
 'flat',
 'flat',
 'br',
 'br',
 'i',
 "don't",
 'know',
 'how',
 'michael',
 'madison',
 'could',
 'have',
 'allowed',
 'this',
 'one',
 'on',
 'his',
 'plate',
 'he',
 'almost',
 'seemed',
 'to',
 'know',
 'this',
 "wasn't",
 'going',
 'to',
 'work',
 'out',
 'and',
 'his',
 'performance',
 'was',
 'quite',
 '',
 '',
 'so',
 'all',
 'you',
 'madison',
 'fans',
 'give',
 'this',
 'a',
 'miss']

In [33]:
var1=decoded_rev.split(' ')

In [34]:
list1=[]
list1.append([word_index.get(i) for i in var1])


In [42]:
list1[0]

[None,
 None,
 588,
 199,
 11,
 28,
 3,
 714,
 7,
 7,
 None,
 None,
 None,
 None,
 2,
 1,
 357,
 4,
 1,
 174,
 5757,
 391,
 351,
 1,
 120,
 6,
 1032,
 1032,
 1032,
 7,
 7,
 10,
 89,
 121,
 86,
 485,
 7941,
 97,
 25,
 1665,
 11,
 28,
 20,
 24,
 7476,
 26,
 217,
 465,
 5,
 121,
 11,
 283,
 167,
 5,
 154,
 43,
 2,
 24,
 236,
 13,
 176,
 None,
 None,
 35,
 29,
 22,
 7941,
 448,
 199,
 11,
 3,
 714]

In [43]:
res = [] 
for val in list1[0]: 
    if val != None : 
        res.append(val) 

In [44]:
res

[588,
 199,
 11,
 28,
 3,
 714,
 7,
 7,
 2,
 1,
 357,
 4,
 1,
 174,
 5757,
 391,
 351,
 1,
 120,
 6,
 1032,
 1032,
 1032,
 7,
 7,
 10,
 89,
 121,
 86,
 485,
 7941,
 97,
 25,
 1665,
 11,
 28,
 20,
 24,
 7476,
 26,
 217,
 465,
 5,
 121,
 11,
 283,
 167,
 5,
 154,
 43,
 2,
 24,
 236,
 13,
 176,
 35,
 29,
 22,
 7941,
 448,
 199,
 11,
 3,
 714]

In [52]:
res=np.array(res)

In [54]:
res.max()

7941

In [55]:
train1=np.zeros((1,10000))
train1[0,res]=1

In [56]:
train1

array([[0., 1., 1., ..., 0., 0., 0.]])

In [58]:
y_predict=model.predict(train1)

In [59]:
np.argmax(y_predict)

0